name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main # or specify any branch you want to trigger this workflow on

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Configure AWS credentials with session token
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }} # Use the session token
        aws-region: us-east-1 # Change to your AWS region

    - name: Get ECR repository URI
      id: ecr_uri
      run: echo "REPO_URI=$(aws ecr describe-repositories --repository-names my-repo --query 'repositories[0].repositoryUri' --output text)" >> $GITHUB_ENV

    - name: Build, tag, and push Docker image
      env:
        ECR_URI: ${{ env.REPO_URI }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_URI:$IMAGE_TAG .
        docker push $ECR_URI:$IMAGE_TAG

    - name: Image digest
      run: |
        IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' ${{ env.REPO_URI }}:${{ github.sha }})
        echo "Docker image pushed: $IMAGE_DIGEST"
